-- HeliumID baseline schema.
--
-- Implements concept §3.2 "Recommended entities" and §3.3 "Indexes and constraints".
--
-- Conventions used throughout:
--   * every timestamp is `timestamptz`; the application always writes UTC.
--   * identifiers are UUIDs generated by the application, never by the database, so an id
--     exists before the row does and can be referenced by events emitted in the same
--     transaction.
--   * anything derived from a credential is stored as a hash or as authenticated ciphertext,
--     never as plaintext. The only exception is `totp_factors.encrypted_secret`, which must be
--     recoverable and is therefore encrypted rather than hashed (§3.2).
--   * `*_normalized` columns carry the single normalization policy from
--     `dev.kamiql.helium.domain.common.Normalization` and are the only columns used for lookup.
--
-- Rollback strategy: this migration is the initial baseline. Undo is `DROP SCHEMA`; there is
-- no partial rollback because there is no prior version. Every subsequent migration follows
-- the expand-and-contract rule from §3.4.

-- ---------------------------------------------------------------------------
-- accounts
-- ---------------------------------------------------------------------------

CREATE TABLE users
(
    id                       uuid PRIMARY KEY,
    username                 varchar(64)  NOT NULL,
    username_normalized      varchar(64)  NOT NULL,
    primary_email            varchar(320) NOT NULL,
    primary_email_normalized varchar(320) NOT NULL,
    first_name               varchar(128) NOT NULL DEFAULT '',
    last_name                varchar(128) NOT NULL DEFAULT '',
    status                   varchar(40)  NOT NULL,
    email_verified_at        timestamptz,
    created_at               timestamptz  NOT NULL,
    updated_at               timestamptz  NOT NULL,
    -- Optimistic locking. Every UPDATE asserts the value it read and bumps it, so two
    -- concurrent profile writes cannot silently overwrite each other.
    version                  bigint       NOT NULL DEFAULT 0,

    CONSTRAINT users_status_check CHECK (status IN
                                         ('PENDING_EMAIL_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'LOCKED', 'DELETED'))
);

-- Uniqueness is enforced on the normalized form only. Enforcing it on the display form as
-- well would let `Alice` and `alice` coexist, which is exactly the confusion this prevents.
CREATE UNIQUE INDEX users_username_normalized_key ON users (username_normalized);
CREATE UNIQUE INDEX users_primary_email_normalized_key ON users (primary_email_normalized);
CREATE INDEX users_status_idx ON users (status);
CREATE INDEX users_created_at_idx ON users (created_at DESC);

CREATE TABLE password_credentials
(
    user_id         uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    password_hash   text        NOT NULL,
    algorithm       varchar(32) NOT NULL,
    -- Cost parameters travel with the hash so raising them does not invalidate existing
    -- credentials; the login flow rehashes transparently on the next successful sign-in.
    parameters_json jsonb       NOT NULL,
    changed_at      timestamptz NOT NULL,
    created_at      timestamptz NOT NULL
);

-- ---------------------------------------------------------------------------
-- authorization: roles and permissions
-- ---------------------------------------------------------------------------

CREATE TABLE roles
(
    name        varchar(64) PRIMARY KEY,
    description text        NOT NULL DEFAULT '',
    color       varchar(16) NOT NULL DEFAULT '#5865F2',
    -- Built-in roles cannot be renamed or deleted through the admin API.
    built_in    boolean     NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL
);

CREATE TABLE role_permissions
(
    role_name  varchar(64)  NOT NULL REFERENCES roles (name) ON DELETE CASCADE,
    permission varchar(128) NOT NULL,
    PRIMARY KEY (role_name, permission)
);

CREATE TABLE user_roles
(
    user_id     uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_name   varchar(64) NOT NULL REFERENCES roles (name) ON DELETE CASCADE,
    assigned_at timestamptz NOT NULL,
    PRIMARY KEY (user_id, role_name)
);

CREATE INDEX user_roles_role_idx ON user_roles (role_name);

-- ---------------------------------------------------------------------------
-- external identities
-- ---------------------------------------------------------------------------

CREATE TABLE external_identities
(
    id             uuid PRIMARY KEY,
    user_id        uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    provider_key   varchar(64)  NOT NULL,
    issuer         varchar(512) NOT NULL,
    subject        varchar(512) NOT NULL,
    provider_email varchar(320),
    profile_json   jsonb        NOT NULL DEFAULT '{}'::jsonb,
    created_at     timestamptz  NOT NULL,
    last_login_at  timestamptz
);

-- The trust anchor. `(issuer, subject)` is the only pair a provider guarantees to be stable
-- and unique; linking by email is an account-takeover vector (§9.4). The unique index is what
-- makes concurrent link attempts safe — the second one fails on the constraint rather than
-- on a stale read.
CREATE UNIQUE INDEX external_identities_issuer_subject_key ON external_identities (issuer, subject);
CREATE UNIQUE INDEX external_identities_user_provider_key ON external_identities (user_id, provider_key);
CREATE INDEX external_identities_user_idx ON external_identities (user_id);

-- ---------------------------------------------------------------------------
-- multi-factor authentication
-- ---------------------------------------------------------------------------

CREATE TABLE mfa_factors
(
    id           uuid PRIMARY KEY,
    user_id      uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type         varchar(32) NOT NULL,
    label        varchar(64) NOT NULL DEFAULT '',
    status       varchar(16) NOT NULL,
    created_at   timestamptz NOT NULL,
    last_used_at timestamptz,

    CONSTRAINT mfa_factors_type_check CHECK (type IN ('TOTP', 'WEBAUTHN', 'RECOVERY_CODE')),
    CONSTRAINT mfa_factors_status_check CHECK (status IN ('PENDING', 'ACTIVE', 'REVOKED'))
);

CREATE INDEX mfa_factors_user_status_idx ON mfa_factors (user_id, status);

CREATE TABLE totp_factors
(
    factor_id           uuid PRIMARY KEY REFERENCES mfa_factors (id) ON DELETE CASCADE,
    -- AES-256-GCM ciphertext in `v<version>.<nonce>.<ciphertext>` form. Encrypted and not
    -- hashed because the server must recompute future codes (§3.2).
    encrypted_secret    text        NOT NULL,
    secret_key_version  integer     NOT NULL,
    algorithm           varchar(16) NOT NULL DEFAULT 'SHA1',
    digits              integer     NOT NULL DEFAULT 6,
    period_seconds      integer     NOT NULL DEFAULT 30,
    -- Replay guard: a code is accepted at most once, even inside its validity window (§4.7).
    last_accepted_step  bigint,
    created_at          timestamptz NOT NULL
);

CREATE TABLE recovery_codes
(
    id         uuid PRIMARY KEY,
    user_id    uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    code_hash  varchar(128) NOT NULL,
    used_at    timestamptz,
    created_at timestamptz NOT NULL
);

CREATE UNIQUE INDEX recovery_codes_hash_key ON recovery_codes (code_hash);
CREATE INDEX recovery_codes_user_idx ON recovery_codes (user_id) WHERE used_at IS NULL;

-- Reserved for the WebAuthn milestone. The table exists now so the migration that starts
-- using it is a code change only. A passkey private key is never stored — only the public key.
CREATE TABLE webauthn_credentials
(
    id                     uuid PRIMARY KEY,
    user_id                uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    credential_id          bytea        NOT NULL,
    public_key             bytea        NOT NULL,
    signature_counter      bigint       NOT NULL DEFAULT 0,
    aaguid                 uuid,
    transports             varchar(128) NOT NULL DEFAULT '',
    user_verified_required boolean      NOT NULL DEFAULT false,
    backup_eligible        boolean      NOT NULL DEFAULT false,
    backup_state           boolean      NOT NULL DEFAULT false,
    rp_id                  varchar(255) NOT NULL,
    created_at             timestamptz  NOT NULL,
    last_used_at           timestamptz
);

CREATE UNIQUE INDEX webauthn_credentials_credential_id_key ON webauthn_credentials (credential_id);
CREATE INDEX webauthn_credentials_user_idx ON webauthn_credentials (user_id);

-- ---------------------------------------------------------------------------
-- one-time tokens
-- ---------------------------------------------------------------------------

-- Email verification, email change and password reset share a structure, so they share a
-- table with an explicit `purpose`. Every lookup filters on purpose, which is what stops a
-- verification token from being redeemed as a password reset.
CREATE TABLE verification_tokens
(
    id         uuid PRIMARY KEY,
    user_id    uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash varchar(128) NOT NULL,
    purpose    varchar(32)  NOT NULL,
    -- For EMAIL_CHANGE, the address being claimed. Never a secret.
    payload    text,
    expires_at timestamptz  NOT NULL,
    used_at    timestamptz,
    created_at timestamptz  NOT NULL,

    CONSTRAINT verification_tokens_purpose_check CHECK (purpose IN
                                                        ('EMAIL_VERIFICATION', 'EMAIL_CHANGE', 'PASSWORD_RESET'))
);

CREATE UNIQUE INDEX verification_tokens_hash_purpose_key ON verification_tokens (token_hash, purpose);
CREATE INDEX verification_tokens_user_purpose_idx ON verification_tokens (user_id, purpose) WHERE used_at IS NULL;
CREATE INDEX verification_tokens_expires_idx ON verification_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- sessions
-- ---------------------------------------------------------------------------

CREATE TABLE sessions
(
    id                    uuid PRIMARY KEY,
    user_id               uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- HMAC of the cookie value. A dump of this table yields no usable session.
    session_hash          varchar(128) NOT NULL,
    client_id             varchar(128),
    created_at            timestamptz  NOT NULL,
    last_seen_at          timestamptz  NOT NULL,
    idle_expires_at       timestamptz  NOT NULL,
    absolute_expires_at   timestamptz  NOT NULL,
    revoked_at            timestamptz,
    -- Last full credential presentation, for step-up checks. Not the same as created_at.
    authenticated_at      timestamptz  NOT NULL,
    -- Comma-separated AMR values; small, closed set, so a join table would be overkill.
    authentication_methods varchar(128) NOT NULL DEFAULT '',
    ip_hash               varchar(128),
    user_agent_hash       varchar(128),
    device_label          varchar(128)
);

CREATE UNIQUE INDEX sessions_hash_key ON sessions (session_hash);
CREATE INDEX sessions_user_revoked_idx ON sessions (user_id, revoked_at);
CREATE INDEX sessions_absolute_expires_idx ON sessions (absolute_expires_at);

-- ---------------------------------------------------------------------------
-- OAuth clients, scopes, consent
-- ---------------------------------------------------------------------------

CREATE TABLE oauth_scopes
(
    name        varchar(128) PRIMARY KEY,
    description text        NOT NULL,
    -- Granted without appearing on the consent screen (`openid`).
    implicit    boolean     NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL
);

CREATE TABLE oauth_clients
(
    client_id          varchar(128) PRIMARY KEY,
    name               varchar(255) NOT NULL,
    type               varchar(16)  NOT NULL,
    -- NULL for public clients. Confidential clients store only a hash, so a leak of this
    -- table does not let an attacker authenticate as the client.
    secret_hash        varchar(128),
    secret_rotated_at  timestamptz,
    -- Only ever true for first-party clients the operator controls.
    skip_consent       boolean      NOT NULL DEFAULT false,
    audiences          varchar(512) NOT NULL DEFAULT '',
    grant_types        varchar(255) NOT NULL,
    enabled            boolean      NOT NULL DEFAULT true,
    created_at         timestamptz  NOT NULL,
    updated_at         timestamptz  NOT NULL,

    CONSTRAINT oauth_clients_type_check CHECK (type IN ('PUBLIC', 'CONFIDENTIAL')),
    -- A public client cannot hold a secret, and a confidential client must.
    CONSTRAINT oauth_clients_secret_check CHECK (
        (type = 'PUBLIC' AND secret_hash IS NULL) OR (type = 'CONFIDENTIAL' AND secret_hash IS NOT NULL))
);

CREATE TABLE oauth_redirect_uris
(
    client_id    varchar(128) NOT NULL REFERENCES oauth_clients (client_id) ON DELETE CASCADE,
    -- Compared with exact string equality. Never normalized, never pattern matched (§4.9).
    redirect_uri varchar(2048) NOT NULL,
    PRIMARY KEY (client_id, redirect_uri)
);

CREATE TABLE oauth_client_scopes
(
    client_id varchar(128) NOT NULL REFERENCES oauth_clients (client_id) ON DELETE CASCADE,
    scope     varchar(128) NOT NULL REFERENCES oauth_scopes (name) ON DELETE CASCADE,
    PRIMARY KEY (client_id, scope)
);

CREATE TABLE consents
(
    id             uuid PRIMARY KEY,
    user_id        uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    client_id      varchar(128) NOT NULL REFERENCES oauth_clients (client_id) ON DELETE CASCADE,
    granted_scopes varchar(1024) NOT NULL,
    granted_at     timestamptz  NOT NULL,
    revoked_at     timestamptz
);

CREATE UNIQUE INDEX consents_user_client_key ON consents (user_id, client_id);

-- ---------------------------------------------------------------------------
-- authorization codes and refresh tokens
-- ---------------------------------------------------------------------------

CREATE TABLE authorization_codes
(
    id                     uuid PRIMARY KEY,
    code_hash              varchar(128)  NOT NULL,
    client_id              varchar(128)  NOT NULL REFERENCES oauth_clients (client_id) ON DELETE CASCADE,
    user_id                uuid          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    session_id             uuid,
    -- Must match the token request byte for byte (RFC 6749 §4.1.3).
    redirect_uri           varchar(2048) NOT NULL,
    scopes                 varchar(1024) NOT NULL,
    nonce                  varchar(255),
    code_challenge         varchar(255)  NOT NULL,
    code_challenge_method  varchar(16)   NOT NULL,
    authentication_methods varchar(128)  NOT NULL DEFAULT '',
    authenticated_at       timestamptz   NOT NULL,
    issued_at              timestamptz   NOT NULL,
    expires_at             timestamptz   NOT NULL,
    consumed_at            timestamptz,

    -- Only S256 exists in the domain enum; the constraint keeps a future bug from writing
    -- `plain` behind the enum's back.
    CONSTRAINT authorization_codes_pkce_check CHECK (code_challenge_method = 'S256')
);

CREATE UNIQUE INDEX authorization_codes_hash_key ON authorization_codes (code_hash);
CREATE INDEX authorization_codes_expires_idx ON authorization_codes (expires_at);

CREATE TABLE refresh_token_families
(
    id                     uuid PRIMARY KEY,
    user_id                uuid          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    client_id              varchar(128)  NOT NULL REFERENCES oauth_clients (client_id) ON DELETE CASCADE,
    session_id             uuid,
    scopes                 varchar(1024) NOT NULL,
    authentication_methods varchar(128)  NOT NULL DEFAULT '',
    created_at             timestamptz   NOT NULL,
    absolute_expires_at    timestamptz   NOT NULL,
    revoked_at             timestamptz,
    -- Set when a used token was presented again. Kept separate from revoked_at so the
    -- security signal survives in the record.
    reuse_detected_at      timestamptz
);

CREATE INDEX refresh_token_families_user_revoked_idx ON refresh_token_families (user_id, revoked_at);
CREATE INDEX refresh_token_families_session_idx ON refresh_token_families (session_id);
CREATE INDEX refresh_token_families_expires_idx ON refresh_token_families (absolute_expires_at);

CREATE TABLE refresh_tokens
(
    id                    uuid PRIMARY KEY,
    family_id             uuid         NOT NULL REFERENCES refresh_token_families (id) ON DELETE CASCADE,
    token_hash            varchar(128) NOT NULL,
    issued_at             timestamptz  NOT NULL,
    expires_at            timestamptz  NOT NULL,
    -- The reuse signal. Used rows are retained until the family expires; deleting them would
    -- make a replayed token look merely unknown.
    used_at               timestamptz,
    revoked_at            timestamptz,
    replaced_by_token_id  uuid
);

CREATE UNIQUE INDEX refresh_tokens_hash_key ON refresh_tokens (token_hash);
CREATE INDEX refresh_tokens_family_idx ON refresh_tokens (family_id);
CREATE INDEX refresh_tokens_expires_idx ON refresh_tokens (expires_at);

-- Access tokens are self-contained JWTs, so revoking one before expiry needs an explicit
-- deny list that `/oauth2/introspect` consults. Bounded by the access-token lifetime.
CREATE TABLE revoked_access_tokens
(
    token_id   varchar(64) PRIMARY KEY,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz NOT NULL
);

CREATE INDEX revoked_access_tokens_expires_idx ON revoked_access_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- signing keys
-- ---------------------------------------------------------------------------

CREATE TABLE signing_keys
(
    id                    varchar(128) PRIMARY KEY,
    algorithm             varchar(16)  NOT NULL,
    public_jwk            text         NOT NULL,
    -- Encrypted with the KMS-backed data key; the version is embedded in the value.
    encrypted_private_key text         NOT NULL,
    status                varchar(16)  NOT NULL,
    created_at            timestamptz  NOT NULL,
    activated_at          timestamptz,
    retires_at            timestamptz,

    CONSTRAINT signing_keys_status_check CHECK (status IN ('PENDING', 'ACTIVE', 'RETIRING', 'RETIRED'))
);

-- At most one key may be signing at any time; enforced by the database rather than by
-- convention, because two ACTIVE keys would make token verification non-deterministic.
CREATE UNIQUE INDEX signing_keys_single_active ON signing_keys ((status)) WHERE status = 'ACTIVE';

-- ---------------------------------------------------------------------------
-- audit and outbox
-- ---------------------------------------------------------------------------

CREATE TABLE audit_logs
(
    id              uuid PRIMARY KEY,
    event_type      varchar(128) NOT NULL,
    outcome         varchar(16)  NOT NULL,
    actor_user_id   uuid,
    subject_user_id uuid,
    client_id       varchar(128),
    request_id      varchar(128) NOT NULL,
    -- Hashed, never raw (§3.2, §7.5).
    ip_hash         varchar(128),
    user_agent_hash varchar(128),
    metadata_json   jsonb        NOT NULL DEFAULT '{}'::jsonb,
    created_at      timestamptz  NOT NULL
);

-- No FK to users: audit rows must outlive the account they describe.
CREATE INDEX audit_logs_subject_created_idx ON audit_logs (subject_user_id, created_at DESC);
CREATE INDEX audit_logs_actor_created_idx ON audit_logs (actor_user_id, created_at DESC);
CREATE INDEX audit_logs_event_created_idx ON audit_logs (event_type, created_at DESC);
CREATE INDEX audit_logs_request_idx ON audit_logs (request_id);

CREATE TABLE outbox_events
(
    id             uuid PRIMARY KEY,
    event_type     varchar(128) NOT NULL,
    aggregate_type varchar(64)  NOT NULL,
    aggregate_id   varchar(128) NOT NULL,
    payload_json   jsonb        NOT NULL,
    attempts       integer      NOT NULL DEFAULT 0,
    available_at   timestamptz  NOT NULL,
    processed_at   timestamptz,
    last_error     text,
    created_at     timestamptz  NOT NULL
);

-- The dispatcher's claim query is `processed_at IS NULL AND available_at <= now()`; a partial
-- index keeps it cheap no matter how much delivered history accumulates.
CREATE INDEX outbox_events_pending_idx ON outbox_events (available_at) WHERE processed_at IS NULL;
CREATE INDEX outbox_events_processed_idx ON outbox_events (processed_at, available_at);

-- ---------------------------------------------------------------------------
-- idempotency
-- ---------------------------------------------------------------------------

CREATE TABLE idempotency_records
(
    idempotency_key varchar(255) NOT NULL,
    flow_id         varchar(128) NOT NULL,
    client_id       varchar(128),
    user_id         uuid,
    -- Hash of the request payload: the same key with a different body is a conflict, not a
    -- replay (§2.5).
    request_hash    varchar(128) NOT NULL,
    status          varchar(16)  NOT NULL,
    response_hash   varchar(128),
    response_body   text,
    created_at      timestamptz  NOT NULL,
    completed_at    timestamptz,
    expires_at      timestamptz  NOT NULL,

    PRIMARY KEY (idempotency_key, flow_id),
    CONSTRAINT idempotency_status_check CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idempotency_records_expires_idx ON idempotency_records (expires_at);
